Create zenip-42002.md
HorizenOfficial/ZenIPs pull request #12
Opened 2022-04-11 18:48 UTC by johnwight

2022-04-11 20:53 UTC, johnwight commented
@rosariopabst, @cronicc, @ptagl please review.

2022-04-14 10:07 UTC, ptagl requested changes

2022-04-14 10:07 UTC, ptagl commented on 42201.md
> +* new fields to `getblocktemplate` RPC command
Can we mention also in this list that we added the "sidechain version" field?
```suggestion
* new field `version` to be specified when creating a sidechain (inside the Sidechain Creation Output)
* new fields to `getblocktemplate` RPC command
```

2022-04-14 10:07 UTC, ptagl commented on 42201.md
> +The enhancements extend functionality for block template requests and to identify both sidechain versions and IDs together. These enhancements have already been implemented with v3.1.0.
When we started working on v3.1.0, the highest priority task was fixing an issue with the deserialization of _Custom Fields_ included in certificates, and after this fix we ended up discovering that we also needed an API to retrieve the `sidechain version` field we introduced to apply such fix. For this reason, if you agree, I would include the _Custom Fields_ issue in the motivation section instead of the API. 
```suggestion
The enhancements fix an issue with the management of `Custom Fields` included in certificates and extend functionality for block template requests. These enhancements have already been implemented with v3.1.0.
```

2022-04-14 10:07 UTC, ptagl commented on 42201.md
> +The Sidechain Creation Output now includes sidechain version information. The `sc_create`, `createrawtransaction`, and `getscinfo` RPC commands are updated to include the `version` argument. This fie
Just for better clarity, I would highlight that `withdrawalEpochLength` has been used to store one byte for the `version` field.
```suggestion
The Sidechain Creation Output now includes sidechain version information. The `sc_create`, `createrawtransaction`, and `getscinfo` RPC commands are updated to include the `version` argument. This field is now mandatory when creating a new sidechain. Also, the `version` field has been added to `CTxScCreationOut` and `ScFixedParamaters`, it is stored in the first byte of the `withdrawalEpochLength`. The `sidechainVersion` parameter is added to `GetFieldElement`.
```

2022-04-14 10:07 UTC, ptagl commented on 42201.md
> +**`getscgensisinfo`extensions**
Is there a space missing here?
```suggestion
**`getscgensisinfo` extensions**
```

2022-04-14 10:07 UTC, ptagl commented on 42201.md
> +The `getscgenesisinfo` RPC command includes` a new list of pairs (`sidechain_id`, `sidechain_version`) for each certificate published in the sidechain genesis block.
I think we have a possible typo here.
```suggestion
The `getscgenesisinfo` RPC command includes a new list of pairs (`sidechain_id`, `sidechain_version`) for each certificate published in the sidechain genesis block.
```

2022-04-15 16:37 UTC, johnwight commented
Implemented all @ptagl suggested feedback.

2022-04-19 03:50 UTC, closed without merging