Update zenip-42000.md
HorizenOfficial/ZenIPs pull request #21
Opened 2023-01-05 22:46 UTC by Eclipse008

Updating the list of Editors and the process for removing Editors should one resign from the organization he or she represents. This is to harmonize ZenIP-42000 with the changes approved via ZenIP-42001.

2023-01-05 22:51 UTC, cronicc requested changes
Please update the status of zenips 42000 and 42001 to `Active`.

2023-01-06 16:59 UTC, cronicc approved these changes

2023-01-06 17:42 UTC, zain-cheng approved these changes

2023-01-10 15:08 UTC, rosariopabst approved these changes

2023-01-10 15:13 UTC, merged