Move ZenIP-42203 from Draft to Final
HorizenOfficial/ZenIPs pull request #26
Opened 2023-07-25 10:59 UTC by ptagl

2023-07-25 12:02 UTC, victHorizen approved these changes

2023-07-25 12:38 UTC, victHorizen requested changes
can you remove Dean from the Owners?

2023-07-25 14:13 UTC, victHorizen approved these changes

2023-07-25 17:49 UTC, cronicc approved these changes

2023-07-26 00:57 UTC, zain-cheng approved these changes

2023-07-26 13:05 UTC, megaluck approved these changes

2023-07-26 13:07 UTC, merged